---
title: Een deel van een kop- of de alinea-tekst animeren
hero_image: images/banner.png
description: Een deel van een kop- of de alinea-tekst animeren.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Een deel van een kop- of de alinea-tekst animeren
