title: Animate part of a header or paragraph text
hero_image: images/banner.png
description: Animate part of a header or paragraph text
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Animate part of a header or paragraph text
