---
title: Animer une partie d'un en-tête ou le texte du paragraphe
hero_image: images/banner.png
description: Anime une partie d'un en-tête ou le texte du paragraphe.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Animer une partie d'un en-tête ou le texte du paragraphe
